# Generated by Django 3.2.6 on 2021-08-15 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registereduser',
            name='profilePic',
            field=models.ImageField(default='default.jpeg', upload_to='profile_pics'),
        ),
    ]
